# Generated by Django 4.0.4 on 2022-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='can_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
